### PR TITLE
Reference latest version on README

### PR DESCRIPTION
**Pull request by data-retriever**

### CODE REVIEW

**Comment by tikue** [comment]
Thanks! Looks like you need to sign the CLA. Sorry about that, I realize this is a tiny change, but I am compelled to follow the rules :(

**Comment by data-retriever** [comment]
If it requires a google account I don't have one and I don't plan on creating one.

**Comment by royrustdev** [comment]
I have opened one PR before and was successfully merged. If @data-retriever is not willing to work on this PR any further, I would love to do it. 
Please let me know. 
Thanks 🙏

**Comment by data-retriever** [comment]
@royrustdev go ahead

**Comment by tikue** [comment]
This was closed by https://github.com/google/tarpc/pull/377. Sorry the CLA hindered your contribution!

**Pull request closed without merging**
