### PR TITLE
Updates Nightly Version

### LINKED ISSUE #197: Build failing for Nightly version 2018-08-25
After updating rust to the latest nightly version (2018-08-25) the crate no longer compiles. 
The compilation aborts due to the following errors: 
```
--> /home/henrique/.cargo/git/checkouts/tarpc-87655b19c07c6cd1/9bd66b7/src/plugins/src/lib.rs:11:13
   |
11 | use syntax::codemap::Span;
   |             ^^^^^^^ Could not find `codemap` in `syntax`

error[E0432]: unresolved import `syntax::util::small_vector`
  --> /home/henrique/.cargo/git/checkouts/tarpc-87655b19c07c6cd1/9bd66b7/src/plugins/src/lib.rs:17:19
   |
17 | use syntax::util::small_vector::SmallVector;
   |                   ^^^^^^^^^^^^ Could not find `small_vector` in `util`
```

### PR DESCRIPTION
**Pull request by HenriqueNogara**
Closes #197

### CODE REVIEW

**Comment by HenriqueNogara** [comment]
I signed it!

**Comment by Boscop** [comment]
Hm, it doesn't work for me with `nightly-2018-09-13`:
```toml
tarpc = "0.12"
tarpc-plugins = { git = "https://github.com/google/tarpc", rev = "5e4b97e" }
```

```
error[E0432]: unresolved import `syntax::codemap`
  --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\tarpc-plugins-0.4.0\src\lib.rs:11:13
   |
11 | use syntax::codemap::Span;
   |             ^^^^^^^ Could not find `codemap` in `syntax`

error[E0432]: unresolved import `syntax::util::small_vector`
  --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\tarpc-plugins-0.4.0\src\lib.rs:17:19
   |
17 | use syntax::util::small_vector::SmallVector;
   |                   ^^^^^^^^^^^^ Could not find `small_vector` in `util`

error[E0432]: unresolved import `syntax::codemap`
  --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\pear_codegen-0.0.16\src\lib.rs:19:13
   |
19 | use syntax::codemap::{Span, DUMMY_SP};
   |             ^^^^^^^ Could not find `codemap` in `syntax`

error[E0023]: this pattern has 6 fields, but the corresponding tuple variant has 4 fields
  --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\pear_codegen-0.0.16\src\lib.rs:66:16
   |
66 |         if let ItemKind::Fn(ref decl, safety, cness, abi, ref generics, ref block) = item.node {
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 4 fields, found 6

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `tarpc-plugins`.
warning: build failed, waiting for other jobs to finish...
error[E0061]: this function takes 4 parameters but 6 parameters were supplied
  --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\pear_codegen-0.0.16\src\lib.rs:70:24
   |
70 |             let node = ItemKind::Fn(decl.clone(), safety, cness, abi, generics.clone(), new_block);
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 4 parameters

error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
   --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\pear_codegen-0.0.16\src\lib.rs:317:9
    |
317 |         ExprKind::Block(block) => {
    |         ^^^^^^^^^^^^^^^^^^^^^^ expected 2 fields, found 1

error[E0369]: binary operation `!=` cannot be applied to type `&syntax::ptr::P<syntax::ast::Expr>`
   --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\pear_codegen-0.0.16\src\lib.rs:303:49
    |
303 |                     if new_params.is_empty() || &new_params[0] != input {
    |                                                 ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: an implementation of `std::cmp::PartialEq` might be missing for `&syntax::ptr::P<syntax::ast::Expr>`

error: aborting due to 5 previous errors

Some errors occurred: E0023, E0061, E0369, E0432.
For more information about an error, try `rustc --explain E0023`.
error: Could not compile `pear_codegen`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Boscop** [comment]
Hm, it also doesn't work with `nightly-2018-08-25` (after I updated to `pear_codegen 0.0.20`):

```
error[E0432]: unresolved import `syntax::codemap`
  --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\tarpc-plugins-0.4.0\src\lib.rs:11:13
   |
11 | use syntax::codemap::Span;
   |             ^^^^^^^ Could not find `codemap` in `syntax`

error[E0432]: unresolved import `syntax::util::small_vector`
  --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\tarpc-plugins-0.4.0\src\lib.rs:17:19
   |
17 | use syntax::util::small_vector::SmallVector;
   |                   ^^^^^^^^^^^^ Could not find `small_vector` in `util`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `tarpc-plugins`.
```

**Comment by HenriqueNogara** [comment]
What if you change your `Cargo.toml` to:
`tarpc = { git = "https://github.com/google/tarpc.git", branch = "master" }`
Does it work?

**Comment by tikue** [comment]
Recent work has been on #199, so it's possible I didn't release this independently.

**Comment by Boscop** [comment]
@HenriqueNogara Like this?
```toml
[dependencies]
tarpc = { git = "https://github.com/google/tarpc", branch = "master" }

[patch.crates-io]
tarpc-plugins = { git = "https://github.com/google/tarpc", rev = "5e4b97e" }
```
It gives the same error.

**Comment by HenriqueNogara** [comment]
@Boscop 

On my `Cargo.toml` i don't have `tarpc-plugins`.

**Comment by tikue** [comment]
Yeah I don't think you need to include tarpc-plugins. You may someday, though, if/when things move to proc-macro.

**Comment by Boscop** [comment]
@tikue But then it complains about `#![plugin(tarpc_plugins)]` and when I remove that, it complains
```
error: cannot find macro `snake_to_camel!` in this scope
error: cannot find macro `ty_snake_to_camel!` in this scope
error: cannot find macro `ty_snake_to_camel!` in this scope
error: cannot find macro `impl_snake_to_camel!` in this scope
```
in my `service!{}`.

**Pull request merged**
