### PR TITLE
Change SyncClient to drive its own execution with an internal reactor::Core.

### LINKED ISSUE #88: Document that with default options, all clients share single event loop
`Options::default()` sets `Options.reactor = None`, which causes `Client::connect` to use [`REMOTE.spawn`](https://github.com/google/tarpc/blob/master/src/client.rs#L345). To my great surprise, `REMOTE` is a [static](https://github.com/google/tarpc/blob/master/src/lib.rs#L168) event loop driven by [a single thread](https://github.com/google/tarpc/blob/master/src/lib.rs#L176). Thus, if `Options::default()` is used, all RPC calls block on a single thread. This should be clearly documented, as that thread will quickly become a big bottleneck for high performance systems.

### LINKED ISSUE #89: SyncClient with event loop driven by current thread
Following the observations in #88, I wanted to modify the code such that the thread *making* an RPC call is the one that drives the event loop. However, there doesn't seem to any way to do this with `SyncClient` as far as I can tell? When you make the function call representing an RPC method, you have no way to *also* make that thread drive the core until the call completes? Of course, with a `FutureClient` you could implement this yourself pretty trivially, but having this be a supported mode of operation for `SyncClient` would be really nice.

### PR DESCRIPTION
**Pull request by tikue**
Adds a `reactor::Core` to `SyncClient` to enable the client to drive its own execution, as one would expect.

Previously, the reactor had to be driven on a separate thread, which was confusing.
This has a couple notable side effects:
  1. `SyncClient` is no longer `Clone`.  This is because `reactor::Core`
     is not `Clone`, and creating one is not infallible
     (`Core::new` returns a `Result`). `try_clone` is added in #96 
  2. `SyncClient` does not use the user-specified `client::Options::handle` or
     `client::Options::remote`, because it constructs its own reactor. This problem will be exacerbated if we do end up making the `Handle` arg of `Options` required for future clients.
  3. `SyncClient` rpcs now take `&mut self` because `reactor::Core::run` takes `&mut self`. I don't see any issue here.

fixes #88, #89 

There was also a bug in tls connecting when using a `Handle` (instead of a `Remote` which is used in all current tests). I refactored the client to use the same code in both code paths, and at the same time was able to remove a lot of unneeded code.

### CODE REVIEW

**Comment by tikue** [comment]
Regarding 1, this is a pretty significant change, but I think it's reasonable because:

1. `SyncClient` is easy mode, so if you need more advanced features you can always drop down to `FutureClient`.
2. A user can always connect multiple times.
3. Not being able to drive execution on the same thread that's blocking on the rpc is a bigger flaw that not having `Clone`.

**Comment by tikue** [comment]
Regarding 2, we could have `sync::Options` and `future::Options`, but it might be better ergonomically to just document the fact that the handle option is not used by the sync client. I don't have a strong opinion here.

**Comment by jonhoo** [comment]
Re `Clone`, I think a neat middle-ground would be to add a `try_clone` method to `SyncClient` which returns a `Result<Self>`. It's not as ergonomic as having the standard `Clone` trait implemented, but makes the removal of `Clone` somewhat less annoying.

Re `Options`, I agree that documenting that it is ignored is probably a decent first step.

**Comment by tikue** [comment]
@jonhoo yes that's what I'm thinking as well. I'm thinking of renaming the Connect traits to `ClientExt` so that future extensions like this can be made more easily.

**Comment by shaladdle** [comment]
Sorry for the delay. `try_clone` sounds like a good solution to the problem. There definitely needs to be some way to use the same underlying TcpConnection from multiple threads in sync world.

**Comment by tikue** [comment]
Merged master.

**Pull request merged**
