### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by krzysztofwos**

### CODE REVIEW

**Comment by krzysztofwos** [comment]
LOL, no way. You have to be nuts. My commit is PUBLIC DOMAIN, do with it as you please.

**Comment by tikue** [comment]
I unfortunately can't accept this without a signed CLA. I double checked to see if there's an exception for trivial commits; there isn't. I guess it's easier for the lawyers this way.

I probably won't get to this myself today, so feel free to reopen if you change your mind.

**Comment by krzysztofwos** [comment]
Perhaps also ask the lawyers what happens if someone later goes and fixes
that typo. That’s basically stealing my public domain idea, regardless of
your CLA, and then claiming it isn’t because this wasn’t known to you.
Whacky position to be in :)

We need to say no to people who make this world unreasonable

Software wants to be Free
And you can make a stand or be a tool

**Comment by vorot93** [comment]
@krzysztofwos IANAL but the typo fix is too trivial to be protected in the court of law. And even if it wasn't it's always possible to simply rephrase the sentence.

Regarding the rest of your comment, I do not think it is reasonable to put a man's livelihood in a perilous position just to make a point. One must learn to pick his fights, so to speak. :)

**Comment by krzysztofwos** [comment]
Yes and I am fighting mine trying to live a life according to immutable
belief in better tomorrow.

One can live a life earning less than the fabled Google salary but dream of
better internet where this sort of nonsense isn’t for a bunch of lawyers to
decide

A man’s effort to further the way to build software is our birthright

It’s the direct exercise of LOGOS, the Divine Word, the ability that God
himself bestowed on man: to transform chaos into order through an act of
speech

In the beginning there was the word and the word was with God and the word
was God

John:1, I believe

Your CLA is preventing me from exercising my religious belief, a right
enshrined in your Constitution

The world is full of nonsense because nobody makes a stand

**Comment by krzysztofwos** [comment]
Someone should start a GoFundMe campaign to pay for a lawyer who will
challenge Google all the way to the Supreme Court, LOL

This is unquestionable example of furthering of knowledge offered freely in
good faith

This cannot be prohibited

#Singularity

**Comment by krzysztofwos** [comment]
Sorry to drag you into this buddy

I have OCD and I really want that typo fixed, now I know it’s there, it
annoys me LOL.

Here’s another argument, your CLA is against neurodiversity.

Finally I think I have a human right to have my anguish relieved since it’s
at no cost to the company at all.

But your masters are trying to put a leash on me and to that I say, over my
dead body!

**Comment by vorot93** [comment]
I believe that this PR has run its course and it's time to move on.

**Comment by tikue** [comment]
I've fixed the typo; I'm sorry for any distress this experience has caused you.

**Pull request closed without merging**
