### PR TITLE
Migrate examples to tarpc::server

### PR DESCRIPTION
**Pull request by garious**
Nice macro, use it

### CODE REVIEW

**Comment by tikue** [comment]
Thanks so much for this!

**Comment by garious** [comment]
@googlebot I signed it!

**Comment by tikue** [comment]
@garious  just waiting for googlebot to check again. Just double checking, did you sign with the email address you used to commit this change?

**Comment by garious** [comment]
@tikue, yes I did use the same email address.  I'll try closing and reopening the PR.

**Comment by garious** [comment]
After signing the CLA, docusign strangely only gave me the option to "Continue", which redirected to https://about.google, and offered no "Finish" button.

**Comment by tikue** [comment]
Ah, that's frustrating. Perhaps try again in a little bit?

**Comment by garious** [comment]
Sure thing

**Comment by garious** [comment]
@googlebot I signed it!

**Comment by tikue** [comment]
I'm reaching out to some Google folks about this issue.

**Pull request merged**
